// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPaths(arg1) {
  return window['go']['main']['App']['AddPaths'](arg1);
}

export function ClearLibrary() {
  return window['go']['main']['App']['ClearLibrary']();
}

export function ClearProgress(arg1) {
  return window['go']['main']['App']['ClearProgress'](arg1);
}

export function GetInitialTracks() {
  return window['go']['main']['App']['GetInitialTracks']();
}

export function GetProgress() {
  return window['go']['main']['App']['GetProgress']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function MediaBaseURL() {
  return window['go']['main']['App']['MediaBaseURL']();
}

export function OpenFiles() {
  return window['go']['main']['App']['OpenFiles']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RemoveTrack(arg1) {
  return window['go']['main']['App']['RemoveTrack'](arg1);
}

export function SaveProgress(arg1, arg2) {
  return window['go']['main']['App']['SaveProgress'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
