// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPaths(arg1:Array<string>):Promise<Array<main.Track>>;

export function ClearLibrary():Promise<void>;

export function ClearProgress(arg1:string):Promise<void>;

export function GetInitialTracks():Promise<Array<main.Track>>;

export function GetProgress():Promise<Record<string, number>>;

export function HideToTray():Promise<void>;

export function MediaBaseURL():Promise<string>;

export function OpenFiles():Promise<Array<main.Track>>;

export function OpenFolder():Promise<Array<main.Track>>;

export function Quit():Promise<void>;

export function RemoveTrack(arg1:string):Promise<void>;

export function SaveProgress(arg1:string,arg2:number):Promise<void>;

export function ShowWindow():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
