// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInitialTracks() {
  return window['go']['main']['App']['GetInitialTracks']();
}

export function MediaBaseURL() {
  return window['go']['main']['App']['MediaBaseURL']();
}

export function OpenFiles() {
  return window['go']['main']['App']['OpenFiles']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
