// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetInitialTracks():Promise<Array<main.Track>>;

export function MediaBaseURL():Promise<string>;

export function OpenFiles():Promise<Array<main.Track>>;

export function OpenFolder():Promise<Array<main.Track>>;

export function Quit():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
